---
title: "The EPA and Oil"
format: html
editor: visual
---

[Home page](https://nmisetic.github.io/mywebsite/)

## [**Introduction**]{.underline}

            One of the most important issues on voters' minds during the 2020 Presidential Election was climate change. Americans are divided on how much action the federal government should take on climate change, with some believing climate change to be a complete hoax. This stark division amongst the electorate has resulted in varying degrees of commitment by the federal government to combating climate change, depending on the elected administration.

            Regardless of which party is in charge of the executive branch, issues relating to climate change fall to the Environmental Protection Agency, or EPA. Since its inception, the EPA has been committed to conducting research in order to create environmental regulations that would benefit the health of the American people.

            Of the many elements that impact climate change, one of the most talked about is American oil production and consumption. This paper will discuss the general history of the EPA, the regulatory process within the agency, and finally how this process plays out when the EPA regulates oil within the U.S.

## [**Brief History of the EPA**]{.underline}

            The 1960's marked the beginning of conversations in America about protecting our environment. In July of 1970, a time of heightened concern regarding air, water, and ground pollution, President Richard Nixon sought to find a way to consolidate federal programs designed to reduce pollution in order to increase efficiency. The President presented Congress with a 37-point message on the environment and efforts that should be taken.[\[1\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn1) His efforts would lead to him signing Reorganization Plan No. 3, which called for the establishment of the Environmental Protection Agency. On December 2, William Ruckelshaus was confirmed by the Senate to be the EPA's first Administrator, marking the official "birthday" of the organization.[\[2\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn2) The current administrator of the EPA is Michael S. Regan. While not a Cabinet department, the EPA administrator is typically given cabinet rank.

            Over its over fifty-year history, the EPA has accomplished a great deal in its mission to protect people and the environment from significant health risks. The agency is responsible for many of the major health and safety acts that are attributable to a significant increase in our quality of life to this day.[\[3\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn3) For example, the EPA passed the nation's first lead paint requirements in 1995. In addition, the 1996 Food Quality Protection Act tightened the standard for allowed pesticides used to grow food. Furthermore, the Safe Drinking Water Act Amendments, also from 1996, improved the sanitation requirements of drinking water for children. A more recent achievement is the rejoining of the Paris Climate Accord. These are only some of the famous environmental regulation reforms that the EPA has undertaken for the goal of improving our quality of life. Other general accomplishments include regulating auto emissions, banning the use of DDT, cleaning up toxic waste, protecting the ozone layer, increasing recycling efforts and revitalizing inner-city brownfields.[\[4\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn4)

## [**The Politics of Oil**]{.underline}

            The United States produces roughly 14,837,640 barrels of oil a day and consumes roughly 19,687,287 barrels a day. In both of these categories, the U.S. ranks number one in the world.[\[5\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn5) From January to June 2022, the price of regular motor gasoline rose 49% and the price of diesel rose 55%.[\[6\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn6) In order to remedy this, President Biden began releasing oil from the nation's strategic oil reserves. These oil reserves were first established by Congress in December of 1975 as a way to reduce the impact of severe energy supply interruptions. Currently, the U.S. has roughly 700 million barrels of oil in these reserves. This decision resulted in the economy and oil becoming a big political issue during the first half of the year. Democrats were furious that Biden was going back on one of his biggest campaign promises, whereas Republicans and others who are generally opposed to the current administration believed that the President was not releasing enough, and thereby letting middle-class families suffer.

            While these events from the year's beginning have brought brief attention to oil as a political tool, the fact of the matter is that oil, the economy, and domestic politics have been intertwined ever since it was first drilled here in 1859. The oil industry accounts for roughly 3% of our nation's GDP.[\[7\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn7) Increasing oil prices has a negative effect on the available supply of other goods because they increase the costs of producing them. Furthermore, big oil conglomerates and lobbying groups have historically had great influence in both the legislative and executive branches. For example, Rex Tillerson, just before becoming the Secretary of State during the Trump administration, was the CEO of ExxonMobil. Additionally, records show that House members who opposed President Biden's environmental agenda received a combined total of \$13.4 million from oil and gas interests.[\[8\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn8) More recently, the President has tried to decrease the nation's dependence on oil. As stated previously, however, current events have made executing said plan difficult, which only highlights the oil industry's influence on the U.S. economy.

            Additionally, oil has shaped how the U.S. conducts international relations, with Saudi Arabia being a perfect example. For example, despite reaching their most tense point in decades, relations between the U.S. and Saudi Arabia remain strong. This is attributable to the U.S.'s dependence on Saudi Arabia for oil and gas prices. When Obama was running for reelection, he turned to King Abdullah of Saudi Arabia for help with decreasing gas prices in the U.S. in order to help his reelection chances.[\[9\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn9) Later, during the Trump administration, the amount of oil the U.S. itself produced skyrocketed. However, as a result of Trump continually signaled to the oil market, and the world, on Twitter that the U.S. no longer needed to rely on Saudi oil, the market no longer took him seriously, forcing him to use more diplomatic language with Crown Prince Mohammed bin Salman when prices in the U.S. began to rise.[\[10\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn10) Lastly, the Biden administration, so far, is taking a stance on Saudi oil similar to that of his predecessor Obama, reiterating their strong relationship. However, it is unclear if this will aid the President, considering that the administration's focus on environmentalism and shockingly high rise in gas prices have resulted in a decrease in economic support as well as major U.S. oil companies leading campaigns against the President.[\[11\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn11)

## [**The Regulatory Process**]{.underline}

            The EPA's authorization to issue environmental regulations is where their executive authority comes from. In order for the regulatory process to begin, a bill needs to become law. Congress must write up and vote on a bill, the President has to sign it, and finally the act must be codified in the *United States Code*. These laws are often vague and therefore do not include the details needed to explain how individuals, businesses, or local governments need to follow them, which is where the EPA comes in.

            While every regulation is developed under different circumstances, the EPA still has a general process. First, the EPA researches an issue and, if the agency can find a solution that addresses the problem completely while causing as little disruption as necessary,[\[12\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn12) must submit their significant rules to the White House Office of Information and Regulatory Affairs for review.[\[13\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn13) Typically, the EPA relies on ethical human trials and surveys in order to determine which regulatory decisions are effective at advancing their goals. After the White House gives the EPA permission to continue with its rule making, they will publish proposed rules into the *Federal Register* so that the public can provide input, which is strongly encouraged by the agency.[\[14\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn14) The EPA collects relevant input and finally drafts the new revised proposal into the *Federal Register*. Finally, once the regulation is completed and printed in the Federal Register, it is codified in the *Code of Federal Regulations*.[\[15\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn15)

## [**Larry Weinstock**]{.underline}

            Larry Weinstock is the Program Innovation Coordinator in the EPA's Office of Air and Radiation, or OAR, and has been since 1999. Throughout multiple administrations, his responsibilities have included identifying problems, initiating change, generating results, and managing long term projects, meaning there is no such thing as a typical day for him.[\[16\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn16) In this role, Weinstock works with the EPA Office of Policy, Economics, and Innovation to develop environmentally responsible program innovations, which makes him heavily involved in the regulations process concerning air pollution.[\[17\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn17) He has also been a senior advisor the Assistant Administrator and Deputy Assistant Administrator of the OAR.[\[18\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn18) Weinstock's passion, which led him to taking a job with the OAR, has always been the clean-up of air pollution.[\[19\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn19)

            Weinstock is also a part-time adjunct professor at The George Washington University Law School, teaching a class on Air Pollution Control. He received a Bachelor of Science at the Rensselaer Polytechnic Institute and received his JD at the George Washington University.[\[20\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn20) Prior to receiving his current position at the EPA, Weinstock held a myriad of smaller positions in the EPA's Office of Radiation and Indoor Air. He was also part of the Office of Water for two years in an advisory role. Before joining the EPA, he practiced environmental litigation for a small law firm in Washington, DC.

## [**Projects Led by Weinstock**]{.underline}

            One of the projects Weinstock was stated as saying he was "proudest of leading was the Community Action for a Renewed Environment Project," or CARE Project.[\[21\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn21) This project was designed to create a model that brings the EPA, state and local governments, and community-based organizations together to collaborate on environmental problem solving. The project reached a total of forty-eight communities in twenty-four states and had a total cost of roughly \$6.5 million. The strategy by which this project was carried out was that the EPA can provide grants to community and local officials in order to gather information on the environmental problems that impact said communities the most, and then let the communities decide the best course of action.[\[22\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn22) "Due to its ability to knock down the barriers between the federal government, state governments, and community-led organizations," Weinstock said, "the CARE Project serves as an excellent case study on how policy and regulations are enacted."[\[23\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn23)

            Another project that Weinstock was equally proud of spearheading was the Waste Isolation Pilot Plant, or WIPP.[\[24\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn24) This was the world's first geological repository for radioactive waste, which led to new regulation standards for disposal, and management. The program was revered for its ability to bring economic development to the communities that it reached, "Particularly in Carlsbad, New Mexico," said Weinstock.[\[25\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn25) What makes this program unique was that it faced little controversy at the national level, which cleared the typical obstacle that is executive and legislative branch politics.[\[26\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn26) Like the CARE Project, the WIPP is an excellent case study regarding how policy gets done due to its lack of political opposition, its ability to carry out its intended goal effectively while also bringing economic development and being the first waste management project of its kind in the world.

            Lastly, during his three-year tenure as Special Assistant to the Deputy Assistant Administrator of the OAR, he assisted in the implementation of the 1990 Amendments to the Clean Air Act. The purpose of this act, originally passed in 1970, was to regulate air emissions from stationary and mobile sources.[\[27\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn27) The 1990 amendments added new provisions to account for growing environmental awareness. This included sections related to ozone and ozone depletion, carbon monoxide, particulate matter, acid rain, new permit and motor vehicle requirements, and types of air toxics.[\[28\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn28)

## [**Key Takeaways on Regulatory Process**]{.underline}

            Thanks to his experience with leading projects for the OAR, Weinstock has significant insight into the factors that impact the regulatory process within the EPA. The first, and most important, is that constant research is a critical component in ensuring the EPA can draft regulations that actually help the public. Employees at the EPA work through this research process for a painstakingly long amount of time. Without thorough research into a potential environmental issue, regulations that the EPA put out can at best simply fail to remedy the problem and at worst waste time and resources that could have been spent elsewhere. Another component to this process that goes overlooked, however, is public input. As stated previously, when new regulations are added to the *Federal Register*, the public has the opportunity to send their thoughts to the agency, whether it be through phone calls or mail. The EPA then sifts through public responses to find ones that could either lead to or contain within them new information that could be useful.[\[29\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn29) If the EPA is able to find such information, and validates that said information as factual, they will incorporate their new findings into the development of the final version of the proposed regulation that will be codified in the *Code of Federal Regulations*.

            Additionally, the priorities and ability of the EPA are based on the presidential administration. Because the president himself is not involved in the day-to-day workings of the agency, his legislative agenda, which is an extension of the administration's views on the role of government in general, and executive appointments have a significant effect on the EPA's ability to act on environmental issues. Weinstock recalls a time working under a previous administration where, when discussing new research and regulations with an official with the Office of Management and Budget, said official claimed that the administration "did not believe in acid rain."[\[30\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn30) Clearly, the politics of any presidential administration has the ability to completely impede the progress and goals the EPA can achieve.

            Lastly, when all is said and done and the EPA's new regulations have been codified in the *Code of Federal Regulations*, the final part of the regulatory process is ensuring that the EPA's new rules are implemented effectively. Typically, when new regulations are created, the federal government mandates state governments to implement these regulations at their own discretion. The common result of this practice, either due to a lack of communication or funding, is that state governments do not implement said regulations to the level of satisfaction that the federal government desires, which creates conflict. In a break from the norm, the CARE Project was unprecedented for its ability to break down the barriers between the federal government and state and local governments. Weinstock attributes this to the project's shift in priority from what the federal government believes the nation as a whole needs to what environmental issues individual communities feel are most important to them.[\[31\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn31) The effects of the project are still felt today as the EPA tries to replicate the success it brought back then, showing how important every step of the regulatory process and beyond are.

## [**Translation to Oil Policy**]{.underline}

            While the regulation of oil drilling and gas companies is regulated by different agencies throughout the federal government, the primary EPA agency responsible for this is the Office of Land and Emergency Management, or OLEM. The main responsibilities of the office are developing guidelines for the land disposal of hazardous waste and underground storage tanks, support state and local governments in redeveloping potentially contaminates sites through the Brownfields program and encourage innovative technologies to address contaminated soil and groundwater.[\[32\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn32) The lessons learned from preexisting literature and the EPA's regulatory process are perfectly applicable to our understanding of how various factors can impact the EPA's process of regulating oil and the oil industry at large. Weinstock's testimony, despite working at the OAR and not on oil policy, is also a great insight into the regulatory process. As parts of the EPA, both the OAR and the OLEM are subject to the same internal and external factors that impact the development of new regulations. As stated previously, these factors would include efficacy of research, political incentives and uncovering new information, and ensuring effective implementation at the state level.

            To begin, the regulatory process cannot start without adequate research being conducted beforehand in order to determine what regulations are required. Typically, this research is conducted within the OLEM, and after the research is complete, as per the regulatory process, the regulation is put into the *Federal Register*. Additionally, information brought forward from the public is also accepted if it is deemed an essential component that was either missed or overlooked in the drafting of the initial regulation.[\[33\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn33) In regard to oil policy specifically, the public input aspect is of greater significance. Due to the many groups that are involved in the oil business,[\[34\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn34) as well as those who seek the devolution of its power, there are many who would propose their own research and data to the EPA in an attempt to shape regulations to their liking. As a result, the first step of the process becomes all the more important when dealing with oil. The EPA must be confident in their own information as well vet outside information that is coming from groups or individuals with vested interests. It is reasonable to assume that a CARE Project successor that is specific to oil regulation would prove highly effective, considering the success of the original.

            Secondly, oil regulation is arguably a more politicized issue compared to Weinstock's work on air pollution and, more specifically, the CARE Project. Many jobs in the U.S. are dependent on the oil industry[\[35\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn35), meaning that efforts to regulate it for the sake of the environment are always met with intense backlash. On the other hand, efforts to deregulate the oil industry are met with backlash from environmentalists. The Keystone XL Pipeline dilemma is the most famous example of this of our time. The federal government does not have great authority, compared to other nations, on the construction of oil pipelines, as it is a state issue.[\[36\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn36) States along the pipelines path were divided, as a result, on whether or not to build it. Texas was the pro-pipeline state leader, and while the Obama administration failed to prevent the beginning of its construction, the Trump administration made decisions that favored the oil industry and pro-pipeline states such as Texas.[\[37\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn37)

            Considering this, it is reasonable to conclude that political incentives have a greater effect in the oil field than others under the EPA's umbrella overall. While hard, however, overcoming this political obstacle course has been achieved before. The WIPP is a perfect example of this. The great success of the project was only possible because political polarization was not an obstacle. If a particular regulation or policy measure can be marketed so that it satisfies either side of the political spectrum, then it will be more likely to pass during an administration that might usually have contradictory goals with the EPA. Therefore, just like with the OAR, the ability of the OLEM to perform exceptional work on oil policy without being impeded by political players is crucial.

            Finally, the last and most overlooked part of the regulatory process is the implementation of those regulations at the state level. If this part of the process is not conducted adequately then all of the work that was put into researching, drafting, pushing through political obstructions, and codifying said regulations will culminate in a wasted effort. The CARE Project highlighted the significance of federal and state government communication in achieving the EPA's desired goals.[\[38\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftn38) The EPA still desires to replicate the positive effects of the project today. The CARE Project can be viewed as an excellent case study that can be transmissible to dealing with the challenges of oil regulation in the current day.

## [**Conclusion**]{.underline}

            Like all other executive agencies, the power and authority of the EPA is largely dependent on the administration's prerogatives and the appointments. Compared to the previous administration, the current EPA is in a position to pass some significant pro-environment regulations. Today, with the looming threat of climate change growing ever greater, the ability of the EPA to regulate the oil industry is more essential than ever.\

## [**Bibliography**]{.underline}

"About the Office of Land and Emergency Management." EPA. Environmental Protection

Agency, September 30, 2022. <https://www.epa.gov/aboutepa/about-office-land-and->

emergency-management. 

AlMuhanna, Ibrahim. "Chapter Eight Barack Obama, Donald Trump, and Joe Biden: A Revolving U.S. Energy Policy." *Oil Leaders*, 2022, 148--74. https://doi.org/10.7312/almu18974-012. 

"The Basics of the Regulatory Process." EPA. Environmental Protection Agency, September 12, 2022. https://www.epa.gov/laws-regulations/basics-regulatory-process. 

"EPA History: Documents about Agency Accomplishments." EPA. Environmental Protection Agency, September 12, 2022. https://www.epa.gov/history/epa-history-documents-about-agency-accomplishments. 

EPA's Rulemaking Process - AGC. Associated General Construction of America, December 2015. https://www.agc.org/sites/default/files/Galleries/enviro_members_file/EPA%20Rulemaking%20Process%20Handout.pdf. 

Just, Robin. "Overview of the EPA Rulemaking Process - Environmental & Energy Law Program." Harvard Law School. Harvard University, January 31, 2020. https://eelp.law.harvard.edu/2019/02/overview-of-the-epa-rulemaking-process/. 

"Larry Weinstock." http://www.law.gwu.edu. The George Washington University. Accessed October 31, 2022. https://www.law.gwu.edu/larry-weinstock. 

Larry Weinstock, interview by Nikola Misetic, October 24, 2022, phone call and recording, The George Washington University. 

Lecours, André, and Daniel Béland. "Federalism and the Politics of Oil and Gas Pipelines in Canada (Alberta) and the United States (Texas)." *Politics & Policy* 50, no. 3 (May 24, 2022): 487--502. https://doi.org/10.1111/polp.12468. 

"The Origins of EPA." EPA. Environmental Protection Agency, June 24, 2022. https://www.epa.gov/history/origins-epa. 

"Record Breaking Increases in Motor Fuel Prices in 2022." Record Breaking Increases in Motor Fuel Prices in 2022 \| Bureau of Transportation Statistics, August 18, 2022. https://www.bts.gov/data-spotlight/record-breaking-increases-motor-fuel-prices-2022. 

"Summary of the Clean Air Act." EPA. Environmental Protection Agency, September 12, 2022. https://www.epa.gov/laws-regulations/summary-clean-air-act. 

"United States Oil." Worldometer. Accessed November 9, 2022.

https://www.worldometers.info/oil/us-oil/. 

"Why Do Oil Prices Matter to the Global Economy? an Expert Explains." World Economic Forum, February 16, 2022. https://www.weforum.org/agenda/2022/02/why-oil-prices-matter-to-global-economy-expert-explains/. 

Zibel, Alan. "Big Oil's Capitol Hill Allies." Public Citizen, February 15, 2021. https://www.citizen.org/article/big-oils-capitol-hill-allies/. 

## Footnotes

[\[1\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref1) "The Origins of EPA," EPA (Environmental Protection Agency, June 24, 2022), https://www.epa.gov/history/origins-epa.

[\[2\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref2) "The Origins of EPA," EPA (Environmental Protection Agency, June 24, 2022), https://www.epa.gov/history/origins-epa.

[\[3\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref3) "EPA History: Documents about Agency Accomplishments," EPA (Environmental Protection Agency, September 12, 2022), https://www.epa.gov/history/epa-history-documents-about-agency-accomplishments.

[\[4\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref4) "EPA History: Documents about Agency Accomplishments," EPA (Environmental Protection Agency, September 12, 2022), https://www.epa.gov/history/epa-history-documents-about-agency-accomplishments.

[\[5\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref5) "United States Oil," Worldometer, accessed November 9, 2022, https://www.worldometers.info/oil/us-oil/.

[\[6\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref6) "Record Breaking Increases in Motor Fuel Prices in 2022," Record Breaking Increases in Motor Fuel Prices in 2022 \| Bureau of Transportation Statistics, August 18, 2022, https://www.bts.gov/data-spotlight/record-breaking-increases-motor-fuel-prices-2022.

[\[7\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref7) "Why Do Oil Prices Matter to the Global Economy? an Expert Explains," World Economic Forum, February 16, 2022, https://www.weforum.org/agenda/2022/02/why-oil-prices-matter-to-global-economy-expert-explains/.

[\[8\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref8) Alan Zibel, "Big Oil's Capitol Hill Allies," Public Citizen, February 15, 2021, https://www.citizen.org/article/big-oils-capitol-hill-allies/.

[\[9\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref9) Ibrahim AlMuhanna, "Chapter Eight Barack Obama, Donald Trump, and Joe Biden: A Revolving U.S. Energy Policy," *Oil Leaders*, 2022, pp. 148-174, https://doi.org/10.7312/almu18974-012, pg. 148.

[\[10\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref10) Ibrahim AlMuhanna, "Chapter Eight Barack Obama, Donald Trump, and Joe Biden: A Revolving U.S. Energy Policy," *Oil Leaders*, 2022, pp. 148-174, https://doi.org/10.7312/almu18974-012, pg. 162.

[\[11\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref11) Ibrahim AlMuhanna, "Chapter Eight Barack Obama, Donald Trump, and Joe Biden: A Revolving U.S. Energy Policy," *Oil Leaders*, 2022, pp. 148-174, https://doi.org/10.7312/almu18974-012, pg. 174.

[\[12\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref12) Robin Just, "Overview of the EPA Rulemaking Process - Environmental & Energy Law Program," Harvard Law School (Harvard University, January 31, 2020), https://eelp.law.harvard.edu/2019/02/overview-of-the-epa-rulemaking-process/.

[\[13\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref13) "EPA's Rulemaking Process - AGC," EPA's Rulemaking Process - AGC (Associated General Construction of America, December 2015), https://www.agc.org/sites/default/files/Galleries/enviro_members_file/EPA%20Rulemaking%20Process%20Handout.pdf.

[\[14\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref14) "The Basics of the Regulatory Process," EPA (Environmental Protection Agency, September 12, 2022), https://www.epa.gov/laws-regulations/basics-regulatory-process.

[\[15\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref15) "The Basics of the Regulatory Process," EPA (Environmental Protection Agency, September 12, 2022), https://www.epa.gov/laws-regulations/basics-regulatory-process.

[\[16\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref16) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[17\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref17) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[18\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref18) "Larry Weinstock," http://www.law.gwu.edu (The George Washington University), accessed October 31, 2022, https://www.law.gwu.edu/larry-weinstock.

[\[19\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref19) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[20\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref20) "Larry Weinstock," http://www.law.gwu.edu (The George Washington University), accessed October 31, 2022, https://www.law.gwu.edu/larry-weinstock.

[\[21\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref21) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[22\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref22) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[23\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref23) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[24\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref24) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[25\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref25) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[26\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref26) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[27\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref27) "Summary of the Clean Air Act," EPA (Environmental Protection Agency, September 12, 2022), https://www.epa.gov/laws-regulations/summary-clean-air-act.

[\[28\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref28) "Summary of the Clean Air Act," EPA (Environmental Protection Agency, September 12, 2022), https://www.epa.gov/laws-regulations/summary-clean-air-act.

[\[29\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref29) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[30\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref30) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[31\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref31) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[32\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref32) "About the Office of Land and Emergency Management," EPA (Environmental Protection Agency, September 30, 2022), https://www.epa.gov/aboutepa/about-office-land-and-emergency-management.

[\[33\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref33) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.

[\[34\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref34) "Why Do Oil Prices Matter to the Global Economy? an Expert Explains," World Economic Forum, February 16, 2022, https://www.weforum.org/agenda/2022/02/why-oil-prices-matter-to-global-economy-expert-explains/.

[\[35\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref35) "Why Do Oil Prices Matter to the Global Economy? an Expert Explains," World Economic Forum, February 16, 2022, https://www.weforum.org/agenda/2022/02/why-oil-prices-matter-to-global-economy-expert-explains/.

[\[36\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref36) André Lecours and Daniel Béland, "Federalism and the Politics of Oil and Gas Pipelines in Canada (Alberta) and the United States (Texas)," *Politics & Policy* 50, no. 3 (May 24, 2022): pp. 487-502, https://doi.org/10.1111/polp.12468, pg. 493.

[\[37\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref37) André Lecours and Daniel Béland, "Federalism and the Politics of Oil and Gas Pipelines in Canada (Alberta) and the United States (Texas)," *Politics & Policy* 50, no. 3 (May 24, 2022): pp. 487-502, https://doi.org/10.1111/polp.12468, pg. 493.

[\[38\]](applewebdata://9F1392FC-DEF6-43BD-B01F-974308B3D331#_ftnref38) Phone interview with Larry Weinstock, Program Innovation Coordinator of the EPA's OAR, on October 24, 2022, by Nikola Misetic.
