---
title: "Is a Happy Ever After Possible for Movie Theaters?"
format: html
editor: visual
---

## by: Nikola Misetic

[Home page](https://nmisetic.github.io/mywebsite/)

The movie industry was hit hard as a result of the Covid-19 pandemic, but communities on Long Island may never recover.

Since the 1930s, the film industry has been one of the most popular forms of entertainment. Cinemas during the \"Golden Age\" of the 1930s and 40s, saw 31 million visits each week, according to the National Science and Media Museum. In the early 2000s, however, this number was roughly 3 million per week.

Today, most people see films on television through terrestrial, satellite, or subscription services, according to the Museum. Although America appears to be the influential film industry, many films are produced internationally. Streaming has become more common as it has become more convenient for modern lifestyles.

The Covid-19 pandemic has greatly hastened the decline of the cinema industry. As a result of social distancing and mask mandates, it has become harder for theaters to sell tickets. According to Florida State University, the US box office alone was projected to lose \$5 billion dollars.

Covid-19 restrictions led many local movie theaters on Long Island to decide to close their doors temporarily until they could turn a profit. Two years later, these doors will never open again. Most theaters that remain on the peninsula are owned by big movie companies AMC and Regal, according to Google Maps.

\"From what I have seen recently, Covid-19 has been the catalyst for businesses going out of business,\" said Robert Pelaez regarding Long Island\'s local theaters. \"Some theaters might have had their own unique problems, but Covid was definitely the straw that broke the camel\'s back.\"

Pelaez is a reporter for The Island Now, which reports local events on Long Island. Pelaez broke the story of the closing of Soundview Cinemas in September, a popular local theater located in Port Washington, due to the pandemic. The theater had closed once before but had reopened in 2013 under new ownership.

\"Soundview closing was absolutely devastating to the community,\" said Eric Holm. \"Everyone was so excited when it opened back up when we were kids. It was a really popular spot to hang out. And now it\'s gone.\"

Holm is a sophomore at GW studying mechanical and aerospace engineering. He has lived on Long Island his entire life. Going to the theater with friends was a big part of his childhood, so these losses had a great impact on him.

Another theater located in Great Neck, Squire Theater, was also shut down a year prior to Soundview. The theater dates back to 1935 and has been a historical staple of the community for decades.

\"Movie theaters are the \'Amazon\' of the entertainment industry,\" Pelaez said. \"As a movie goer myself, I realize how essential the local theater is to a community. It\'s something many people love, and lately have taken for granted. You never know what you truly have until it\'s gone.\"

The pandemic has increased the growing popularity of streaming services as an alternative to movie theaters. In 2020, Disney released Black Widow on their streaming service, Disney+, and in theaters on the same day. The movie generated \$500 million total, and Disney+ generated a quarter of that.

Lost profits due to the pandemic will make it hard for local theaters to afford ways to entice people back. This will dissuade potential new owners, meaning Long Island might have lost its local theaters for good.

\"They\'ll have to adapt, maybe attract an older crowd with new promotions\" Pelaez said. \"Unless you\'re AMC, you don\'t necessarily have the funds to do these things. The streaming war is coming in full force, and it\'s not looking good for theaters.\"
